Repository polkaswitch/polkaswitch-ui, pull requests merged in 2022-02, with the labels that each got.

#110 Enable Moonriver and Harmony on PROD
  public/config/main.config.json
Labels: ready to review

#112 Housekeeping and code quality
  .eslintrc.json
  src/client/js/components/partials/TxCrossChainActiveStatusView.jsx
  src/client/js/components/partials/TxCrossChainHistoricalStatusView.jsx
  src/client/js/components/partials/TxStatusView.jsx
  src/client/js/components/partials/bridge/AvailableRoutes.jsx
  src/client/js/components/partials/bridge/BridgeFinalResultSlide.jsx
  src/client/js/components/partials/bridge/BridgeRouteBox.jsx
  src/client/js/components/partials/connext/ConnextTxTrackerView.jsx
  src/client/js/index.js
Labels: help wanted, ready to review

#114 Fix swapConfig persistency on Swap tab
  src/client/js/components/partials/bridge/BridgeWidget.jsx
  src/client/js/components/partials/swap/SwapWidget.jsx
  src/client/js/components/partials/swap/TradingViewChart.jsx
  src/client/js/index.js
  src/client/js/utils/global.js
  src/client/js/utils/tokenList.js
Labels: WIP

#118 Updated price impact issue.
  src/client/css/custom/swap.scss
  src/client/js/components/partials/bridge/BridgeWidget.jsx
  src/client/js/components/partials/swap/SwapConfirmSlide.jsx
  src/client/js/components/partials/swap/SwapTransactionDetails.jsx
  src/client/js/components/partials/swap/SwapWidget.jsx
  src/client/js/components/partials/swap/TradingViewChart.jsx
  src/client/js/constants/Status.jsx
  src/client/js/constants/index.js
  src/client/js/utils/coingecko.js
  src/client/js/utils/hop.js
  src/client/js/utils/nxtp.js
  src/client/js/utils/swapFn.js
Labels: ready to review

#111 [Feature] Improve cross chain TX history and status - Part 1
  src/client/css/custom/notifications.scss
  src/client/js/components/partials/TxCrossChainActiveStatusView.jsx
  src/client/js/components/partials/TxCrossChainHistoricalStatusView.jsx
  src/client/js/components/partials/TxExplorerLink.jsx
  src/client/js/components/partials/TxHistoryModal.jsx
  src/client/js/components/partials/bridge/BridgeFinalResultSlide.jsx
  src/client/js/components/partials/bridge/BridgeOrderSlide.jsx
  src/client/js/components/partials/bridge/CrossSwapProcessSlide.jsx
  src/client/js/utils/cbridge.js
  src/client/js/utils/hop.js
  src/client/js/utils/nxtp.js
  src/client/js/utils/txBridgeManager.js
Labels: ready to review

#121 [Feature] Jest + @testing-library environment and update the GH Jobs
  .babelrc
  .eslintrc.json
  .github/workflows/node.js.yml
  babel.config.js
  jest.config.js
  jest/__mocks__/fileMock.js
  jest/__mocks__/styleMock.js
  jest/scripts/setupTests.js
  package.json
  src/client/js/components/pages/tests/StakeHome.test.jsx
  src/client/js/components/pages/tests/StatusHome.test.jsx
  src/client/js/components/pages/tests/TokenClaimHome.test.jsx
  src/client/js/components/partials/BridgeButton.jsx
  src/client/js/components/partials/ConnectWalletModal.jsx
  src/client/js/components/partials/GasPriceControl.jsx
  src/client/js/components/partials/NetworkDropdown.jsx
  src/client/js/components/partials/TokenSearchBar.jsx
  src/client/js/components/partials/TokenSearchSlide.jsx
  src/client/js/components/partials/swap/AlphaOnboardingCard.jsx
  src/client/js/components/partials/swap/ChartRangeSelector.jsx
  src/client/js/components/partials/swap/SwapWidget.jsx
  src/client/js/components/partials/swap/TokenSwapDistribution.jsx
  src/client/js/components/tests/index.test.jsx
Labels: ready to review

#122 [Fix] Estimate bridges value overflow
  src/client/js/components/partials/bridge/AdditionalInfoItem.jsx
  src/client/js/components/partials/bridge/BridgeRouteBox.jsx
  src/client/js/components/partials/bridge/RouteItemView.jsx
  src/client/js/components/partials/bridge/SwapRouteBox.jsx
  src/client/js/components/partials/bridge/TokenNetworkRouteBox.jsx
Labels: bug, ready to review

#124 [Fix] decimal issue for get estimate within bridges routes
  src/client/js/components/partials/bridge/BridgeWidget.jsx
  src/client/js/utils/global.js
  src/client/js/utils/txBridgeManager.js
Labels: bug, ready to review
