Repository polkaswitch/polkaswitch-ui, pull requests merged in 2022-01, with the labels that each got.

#96 Fix issue on moonriver single swap
  public/config/test.config.json
  public/tokens/1285.list.json
Labels: ready to review

#92 [FEATURE] Enable status tab on main menu - Rework
  .gitignore
  src/client/css/custom/status.scss
  src/client/css/index.scss
  src/client/js/components/App.jsx
  src/client/js/components/pages/StatusHome.jsx
  src/client/js/components/pages/WalletHome.jsx
  src/client/js/components/pages/useLoadBalance.js
  src/client/js/components/partials/navbar/NavMenu.jsx
  src/client/js/components/partials/wallet/EmptyBalances.jsx
  src/client/js/context/balance.js
Labels: ready to review

#97 [FIX] Disconnected state UI for status tab
  src/client/css/custom/status.scss
  src/client/js/components/pages/StatusHome.jsx
Labels: bug

#99 Updated the contract address of Moonriver aggregator.
  public/config/main.config.json
  public/config/test.config.json
Labels: ready to review

#100 [Fix] Typo within cross-chain/swap confirmation msg
  .eslintrc.json
  src/client/js/components/partials/bridge/CrossSwapProcessSlide.jsx
  src/client/js/components/partials/swap/SwapConfirmSlide.jsx
Labels: bug

#103 [Feature] Improve code quality using ES6 for bridge related files
  src/client/js/components/partials/TokenSearchSlide.jsx
  src/client/js/components/partials/bridge/BridgeWidget.jsx
  src/client/js/utils/cbridge.js
  src/client/js/utils/hop.js
  src/client/js/utils/nxtp.js
  src/client/js/utils/txBridgeManager.js
  src/client/js/utils/txQueue.js
Labels: ready to review

#105 Update bsc platform for single swap
  public/abi/test/Bsc.json
  public/config/main.config.json
  public/config/test.config.json
  src/client/js/components/partials/swap/TokenSwapDistribution.jsx
  src/client/js/utils/swapFn.js
  src/client/js/utils/tokenList.js
  src/client/js/utils/wallet.js
Labels: ready to review

#106 Update line chart graph for trading view
  src/client/js/components/partials/swap/TradingViewChart.jsx
Labels: ready to review

#108 fix aurora issue
  public/config/main.config.json
  public/config/test.config.json
  public/tokens/1313161554.list.json
Labels: ready to review

#107 fix issue of moonriver chain id
  src/client/js/utils/swapFn.js
Labels: ready to review

#80 Bridge Phase 2
  src/client/css/custom/bridge.scss
  src/client/css/custom/layout.scss
  src/client/css/custom/swap.scss
  src/client/js/components/partials/AdvancedSettingsSlide.jsx
  src/client/js/components/partials/TokenSearchSlide.jsx
  src/client/js/components/partials/bridge/AvailableRoutes.jsx
  src/client/js/components/partials/bridge/BridgeOrderSlide.jsx
  src/client/js/components/partials/bridge/BridgeRouteBox.jsx
  src/client/js/components/partials/bridge/BridgeWidget.jsx
  src/client/js/components/partials/bridge/RouteItemView.jsx
  src/client/js/components/partials/bridge/RouteItemWrapper.jsx
  src/client/js/components/partials/bridge/SwapRouteBox.jsx
  src/client/js/components/partials/bridge/TokenNetworkRouteBox.jsx
  src/client/js/utils/cbridge.js
  src/client/js/utils/storage.js
  src/client/js/utils/txBridgeManager.js
Labels: WIP
